export const UI_TEXT = {
  ja: {
    sphere: "Sphere",
    map: "マップ",
    preset: "プリセット",
    apply: "適用",
    seed: "Seed 追加",
    importMd: "MD 読込",
    topic: "トピック",
    node: "ノード",
    searchFilter: "検索 / フィルタ",
    history: "履歴",
    topicLinks: "トピックリンク",
    markdownJson: "Markdown / JSON",
    pageRank: "PageRank",
    target: "対象",
    relation: "関係",
    meaning: "意味",
    search: "検索",
    layer: "レイヤー",
    group: "グループ",
    snapshot: "スナップショット",
    applyFrame: "適用",
    resolve: "解決...",
    language: "言語",
    presetGuide: "プリセットガイド",
    x: "X",
    y: "Y",
    z: "Z",
    snapSphere: "球面へ整列",
  },
  en: {
    sphere: "Sphere",
    map: "Map",
    preset: "Preset",
    apply: "apply",
    seed: "seed",
    importMd: "Import MD",
    topic: "Topic",
    node: "Node",
    searchFilter: "Search / Filter",
    history: "History",
    topicLinks: "Topic Links",
    markdownJson: "Markdown / JSON",
    pageRank: "PageRank",
    target: "Target",
    relation: "Relation",
    meaning: "Meaning",
    search: "Search",
    layer: "Layer",
    group: "Group",
    snapshot: "snapshot",
    applyFrame: "apply",
    resolve: "resolve...",
    language: "Language",
    presetGuide: "Preset Guide",
    x: "X",
    y: "Y",
    z: "Z",
    snapSphere: "snap sphere",
  },
} as const;

export type UiText = (typeof UI_TEXT)[keyof typeof UI_TEXT];
